#!/usr/bin/env python3
"""Context Compiler step for Context Assertions (RFC-0001 v2).

Runs on the host as part of `orcan sync`, after apply-config.py has written
runtime-config.json. For each enabled workspace, in order:

1. **Import the inbox** — <meta_path>/.orcan/context-inbox/*.json, dropped by
   the in-container `orcan-context-propose` tool. Two payload shapes:
     - a new candidate (has `content`/`justification`) becomes a real,
       git-versioned proposal via context_assertions.propose(); a drop that
       already carries a human decision (made interactively, in-session) is
       immediately accepted/rejected too.
     - a "reconsider" flag (has `flag_existing_id`) marks an already-accepted
       assertion for human review, without creating anything new. It is
       recorded in <meta_path>/.orcan/context-flags/<id>.json until resolved.
   Malformed or unresolvable drops are quarantined (renamed `*.invalid`),
   never silently dropped, never allowed to crash the rest of `orcan sync`.
2. **Apply queued decisions** — <meta_path>/.orcan/context-decisions/*.json,
   dropped by the in-container `orcan-context-review` tool: `accept`/`reject`
   transition a `proposed` id; `retire`/`keep` resolve a flagged id (`retire`
   calls context_assertions.retire(), `keep` just clears the flag). Every
   decision clears any matching flag file. Idempotent: a decision for an id
   that's no longer in the expected status is just discarded.
3. **Regenerate the review queue** — <meta_path>/.orcan/context-review-queue.json,
   a host-generated, read-only-for-the-container `{"candidates": [...],
   "reconsider": [...]}` view. This is the only way `orcan-context-review`
   ever sees pending items — it never reads $ORCAN_DATA/context directly,
   same invariant as the agent never seeing the raw store.
4. **Compile** — the existing Applicability Layer + render step, unchanged:
   build the Context Signature, match `accepted` assertions, render
   CONTEXT-ASSERTIONS.md (or remove it if nothing matches). Each rendered
   item's id is included so it can be referenced by a later --flag-existing.

Steps 1-3 only ever produce proposed/accepted/rejected/retired transitions
through context_assertions.py's own public functions — never automatic
acceptance, and no automated process (including the batched Reflection tool,
orcan-context-reflect) can skip the human decision in step 2. See
docs/en/ideas/context-assertions.md.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import context_assertions as ca  # noqa: E402

OUTPUT_NAME = "CONTEXT-ASSERTIONS.md"
INBOX_DIRNAME = "context-inbox"
DECISIONS_DIRNAME = "context-decisions"
FLAGS_DIRNAME = "context-flags"
REVIEW_QUEUE_NAME = "context-review-queue.json"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _describe_relations(relations: list[dict]) -> list[str]:
    lines = []
    for rel in relations or []:
        target_project = rel.get("target_project")
        target_id = rel.get("target_id")
        label = target_id
        if target_project and target_id:
            try:
                target = ca.get_object(Path(target_project), target_id)
                label = f"{target['title']!r} (`{target_id}`)"
            except SystemExit:
                label = f"`{target_id}` (unresolved)"
        lines.append(f"{rel.get('type')} → {label}")
    return lines


def render_markdown(workspace_name: str, items: list[dict], projects: list[dict[str, str]]) -> str:
    signature = ca.build_signature(workspace_name, projects)
    lines = [
        "<!-- Generated by orcan sync (Context Assertions / Applicability Layer)",
        "     — do not edit by hand. Propose changes with:",
        "     orcan context assert propose -->",
        "",
        f"# Context Assertions — {workspace_name}",
        "",
        "Compiled artifact, not notes: every item below was selected because it",
        "matched this workspace's current Context Signature (repos present,",
        "branches) against a human-accepted applicability predicate. See",
        "`orcan context assert list --project <path>` for the full store,",
        "including anything that did **not** match and so is absent here.",
        "",
        "## Workspace composition",
        "",
    ]
    for repo in signature["repos"]:
        branch = signature["branches"].get(repo) or "?"
        lines.append(f"- `{repo}` @ `{branch}`")
    lines.append("")
    if not items:
        lines.append("No accepted assertions currently apply to this composition yet.")
        lines.append("")
    for item in items:
        epistemic = item.get("epistemic_status", "fact")
        criticality = item.get("criticality", "normal")
        lines.append(f"## {item['title']}")
        lines.append("")
        lines.append(
            f"*id: `{item['id']}` · kind: {item['kind']} · epistemic status: {epistemic} · "
            f"criticality: {criticality} · anchor: `{item['anchor_path']}`*"
        )
        lines.append("")
        lines.append(f"**Problem it solves:** {item['justification']}")
        lines.append("")
        lines.append(f"**Selected because:** {'; '.join(item['justification_trail'])}")
        relation_lines = _describe_relations(item.get("relations") or [])
        if relation_lines:
            lines.append("")
            lines.append(f"**Relations:** {'; '.join(relation_lines)}")
        lines.append("")
        lines.append(item["content"])
        lines.append("")
    return "\n".join(lines)


def _projects_by_name(ws: dict) -> dict[str, Path]:
    return {
        str(p["name"]): Path(p["path"])
        for p in (ws.get("projects") or [])
        if p.get("name") and p.get("path")
    }


def _quarantine(path: Path, reason: str) -> None:
    print(f"warning: {path}: {reason} — quarantined", file=sys.stderr)
    dest = path.with_name(path.name + ".invalid")
    try:
        path.replace(dest)
    except OSError:
        pass


def _process_inbox(orcan_dir: Path, projects: dict[str, Path]) -> None:
    inbox = orcan_dir / INBOX_DIRNAME
    if not inbox.is_dir():
        return
    flags_dir = orcan_dir / FLAGS_DIRNAME
    for drop in sorted(inbox.glob("*.json")):
        try:
            payload = json.loads(drop.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            _quarantine(drop, "invalid JSON")
            continue

        project_name = str(payload.get("project_name") or "")
        project_path = projects.get(project_name)
        if project_path is None:
            _quarantine(drop, f"unknown project {project_name!r}")
            continue

        flag_id = str(payload.get("flag_existing_id") or "").strip()
        if flag_id:
            try:
                existing = ca.get_object(project_path, flag_id)
            except SystemExit:
                _quarantine(drop, f"unknown assertion id {flag_id!r}")
                continue
            if existing["status"] != "accepted":
                _quarantine(
                    drop, f"assertion {flag_id!r} is not accepted (status={existing['status']!r})"
                )
                continue
            flags_dir.mkdir(parents=True, exist_ok=True)
            (flags_dir / f"{flag_id}.json").write_text(
                json.dumps(
                    {
                        "id": flag_id,
                        "project_name": project_name,
                        "reason": str(payload.get("reason") or "").strip() or "(no reason given)",
                        "flagged_at": _now_iso(),
                    },
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            drop.unlink(missing_ok=True)
            continue

        content = str(payload.get("content") or "").strip()
        justification = str(payload.get("justification") or "").strip()
        if not content or not justification:
            _quarantine(drop, "missing content or justification")
            continue

        try:
            obj = ca.propose(
                project_path,
                content=content,
                justification=justification,
                title=str(payload.get("title") or ""),
                kind=str(payload.get("kind") or "fact"),
                applicability=payload.get("applicability") or {},
                epistemic_status=str(payload.get("epistemic_status") or "fact"),
                criticality=str(payload.get("criticality") or "normal"),
                relations=payload.get("relations") or [],
            )
        except SystemExit:
            _quarantine(drop, "rejected by context_assertions.propose()")
            continue

        decision = payload.get("decision")
        if decision == "accept":
            ca.accept(project_path, obj["id"])
        elif decision == "reject":
            ca.reject(project_path, obj["id"])
        drop.unlink(missing_ok=True)


def _process_decisions(orcan_dir: Path, projects: dict[str, Path]) -> None:
    decisions_dir = orcan_dir / DECISIONS_DIRNAME
    if not decisions_dir.is_dir():
        return
    flags_dir = orcan_dir / FLAGS_DIRNAME
    for drop in sorted(decisions_dir.glob("*.json")):
        try:
            payload = json.loads(drop.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            _quarantine(drop, "invalid JSON")
            continue

        project_path = projects.get(str(payload.get("project_name") or ""))
        object_id = str(payload.get("id") or "")
        decision = payload.get("decision")
        if project_path is None or not object_id or decision not in ("accept", "reject", "retire", "keep"):
            _quarantine(drop, "malformed decision")
            continue

        try:
            if decision == "accept":
                ca.accept(project_path, object_id)
            elif decision == "reject":
                ca.reject(project_path, object_id)
            elif decision == "retire":
                ca.retire(project_path, object_id)
            # "keep": no store mutation — just clears the flag below
        except SystemExit:
            pass  # already resolved, or wrong status — decisions are idempotent, not fatal

        (flags_dir / f"{object_id}.json").unlink(missing_ok=True)
        drop.unlink(missing_ok=True)


def _write_review_queue(orcan_dir: Path, projects: dict[str, Path]) -> None:
    candidates = []
    for name, path in projects.items():
        for entry in ca.list_objects(path, status="proposed"):
            full = ca.get_object(path, entry["id"])
            candidates.append(
                {
                    "id": full["id"],
                    "project_name": name,
                    "title": full["title"],
                    "content": full["content"],
                    "justification": full["justification"],
                    "kind": full["kind"],
                    "applicability": full["applicability"],
                    "epistemic_status": full.get("epistemic_status", "fact"),
                    "criticality": full.get("criticality", "normal"),
                    "relations": full.get("relations", []),
                    "created_at": full["created_at"],
                }
            )
    candidates.sort(key=lambda i: i["created_at"])

    reconsider = []
    flags_dir = orcan_dir / FLAGS_DIRNAME
    if flags_dir.is_dir():
        for flag_file in sorted(flags_dir.glob("*.json")):
            try:
                flag = json.loads(flag_file.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                flag_file.unlink(missing_ok=True)
                continue
            project_path = projects.get(str(flag.get("project_name") or ""))
            object_id = str(flag.get("id") or "")
            if project_path is None or not object_id:
                flag_file.unlink(missing_ok=True)
                continue
            try:
                full = ca.get_object(project_path, object_id)
            except SystemExit:
                flag_file.unlink(missing_ok=True)  # stale flag, id gone
                continue
            if full["status"] != "accepted":
                flag_file.unlink(missing_ok=True)  # already resolved another way
                continue
            reconsider.append(
                {
                    "id": full["id"],
                    "project_name": flag.get("project_name"),
                    "title": full["title"],
                    "content": full["content"],
                    "justification": full["justification"],
                    "reason": flag.get("reason"),
                    "flagged_at": flag.get("flagged_at") or "",
                }
            )
    reconsider.sort(key=lambda i: i["flagged_at"])

    queue_path = orcan_dir / REVIEW_QUEUE_NAME
    orcan_dir.mkdir(parents=True, exist_ok=True)
    queue_path.write_text(
        json.dumps({"candidates": candidates, "reconsider": reconsider}, indent=2) + "\n",
        encoding="utf-8",
    )


def compile_workspace(ws: dict) -> None:
    meta_path = Path(ws["meta_path"])
    if not meta_path.is_dir():
        return
    dest = meta_path / OUTPUT_NAME
    projects_list = [p for p in (ws.get("projects") or []) if p.get("path") and p.get("name")]
    projects = _projects_by_name(ws)

    orcan_dir = meta_path / ".orcan"
    if projects:
        orcan_dir.mkdir(parents=True, exist_ok=True)
        _process_inbox(orcan_dir, projects)
        _process_decisions(orcan_dir, projects)
        _write_review_queue(orcan_dir, projects)

    if not projects_list:
        dest.unlink(missing_ok=True)
        return
    name = ws.get("name") or "workspace"
    items = ca.select_for_workspace(name, projects_list)
    dest.write_text(render_markdown(name, items, projects_list) + "\n", encoding="utf-8")
    if not items:
        print(f"context: 0 assertions compiled for workspace '{name}'")
        return
    print(f"context: {len(items)} assertion(s) compiled into CONTEXT-ASSERTIONS.md for workspace '{name}'")


def main() -> None:
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
    runtime_path = root / "mounts" / "runtime-config.json"
    if not runtime_path.is_file():
        return
    runtime = json.loads(runtime_path.read_text(encoding="utf-8"))
    for ws in runtime.get("workspaces") or []:
        if ws.get("enabled") is False:
            continue
        compile_workspace(ws)


if __name__ == "__main__":
    main()
