# Appearance
set -g status-bg black
set -g status-fg colour244
set -g window-status-current-style fg=colour226

# Modifier & Configure
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix
unbind %
bind-key | split-window -h
unbind '"'
bind-key - split-window -v
set -sg escape-time 0

# Terminal
set -g default-terminal screen-256color
set -g status-keys vi
set-window-option -g automatic-rename on
set-option -g set-titles on
set -g renumber-windows on
set-option -g allow-rename off
set -g history-limit 100000
set -g display-time 2000
set -g status-interval 5
set -g focus-events on
setw -g aggressive-resize on
set -g set-titles-string "#I:#W [#P:#{pane_current_command}]"

# Terminal status bar 
set -g status-left "#[bold]#S"
#set -g status-right "#(whoami) | %Y-%m-%d %H:%M"


# Start index of Panes and Windows
set -g base-index 1
setw -g pane-base-index 1

# Mouse
bind -n M-a set -g mouse on
bind -n M-q set -g mouse off

# Panes
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

bind -n C-Down  split-window -v
bind -n C-Up    split-window -v -b
bind -n C-Right split-window -h
bind -n C-Left  split-window -h -b

bind -n C-M-Left  previous-window
bind -n C-M-Right next-window

bind -n M-Enter resize-pane -Z

# Create windows
bind -n M-c new-window

# Swap windows
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# Kill tab instantly
bind-key x kill-pane

# Control tabs
bind 0 select-window -t:$
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t:$

# Clipboard
set-option -g set-clipboard on
#bind -n C-t run "tmux save-buffer - > /dev/clipboard"

