#!/usr/bin/env bash
# Docker Compose wrappers — files from ORCAN_ROOT, env/overlays from ORCAN_HOME.
# shellcheck shell=bash

# $1 env-var override, $2 basename under ORCAN_RUNTIME_DIR when it is unset.
_orcan_compose_file() {
    local override="${1:-}"
    if [[ -n "${override}" ]]; then
        printf '%s\n' "${override}"
    else
        printf '%s\n' "${ORCAN_RUNTIME_DIR}/${2}"
    fi
}

orcan_compose_projects_file() {
    _orcan_compose_file "${ORCAN_COMPOSE_PROJECTS:-}" compose-projects.generated.yml
}

orcan_compose_git_file() {
    _orcan_compose_file "${ORCAN_COMPOSE_GIT:-}" compose-git.generated.yml
}

orcan_compose_github_file() {
    _orcan_compose_file "${ORCAN_COMPOSE_GITHUB:-}" compose-github.generated.yml
}

orcan_compose_gitlab_file() {
    _orcan_compose_file "${ORCAN_COMPOSE_GITLAB:-}" compose-gitlab.generated.yml
}

# glab uses the same token family for gitlab.com and self-managed instances.
orcan_prepare_gitlab() {
    local traced=0
    if [[ $- == *x* ]]; then
        traced=1
        set +x
    fi
    local hostname="$1" token="${GITLAB_TOKEN:-${GITLAB_ACCESS_TOKEN:-${OAUTH_TOKEN:-}}}" gitlabf
    if [[ -z "$token" ]] && command -v glab >/dev/null 2>&1; then
        token="$(env -u GITLAB_TOKEN -u GITLAB_ACCESS_TOKEN -u OAUTH_TOKEN -u CI_JOB_TOKEN \
            -u GLAB_ENABLE_CI_AUTOLOGIN GLAB_DEBUG= GLAB_DEBUG_HTTP=false GLAB_CHECK_UPDATE=false DEBUG= \
            glab config get token --host "$hostname" 2>/dev/null)" || token=""
    fi
    if [[ -z "$token" || "$token" == *[$'\r\n']* ]]; then
        orcan_die "GitLab authentication unavailable for ${hostname}: set GITLAB_TOKEN or run glab auth login --hostname ${hostname} on this host"
        return 1
    fi
    export ORCAN_GITLAB_TOKEN="$token"
    gitlabf="$(orcan_compose_gitlab_file)"
    mkdir -p "$(dirname "$gitlabf")" || return
    {
        printf '# Generated by orcan up --gitlab; token resolved only at launch.\n'
        printf 'services:\n  orcan:\n    environment:\n'
        printf '      GITLAB_HOST: "%s"\n' "$hostname"
        printf '      GITLAB_TOKEN: "${ORCAN_GITLAB_TOKEN:-}"\n'
        printf '      GITLAB_ACCESS_TOKEN: ""\n      OAUTH_TOKEN: ""\n'
        printf '      CI_JOB_TOKEN: ""\n      GLAB_ENABLE_CI_AUTOLOGIN: "false"\n'
    } >"$gitlabf" || return
    if ((traced)); then set -x; fi
}

# Resolve credentials in memory. The overlay and launch records contain no token.
# Call only from up, before stopping the current container. Never print gh output.
orcan_prepare_github() {
    local traced=0
    if [[ $- == *x* ]]; then
        traced=1
        set +x
    fi
    local hostname="$1" token="" token_var="GH_ENTERPRISE_TOKEN" githubf
    if [[ "$hostname" == github.com || "$hostname" == *.ghe.com ]]; then
        token_var="GH_TOKEN"
        token="${GH_TOKEN:-${GITHUB_TOKEN:-}}"
    else
        token="${GH_ENTERPRISE_TOKEN:-${GITHUB_ENTERPRISE_TOKEN:-}}"
    fi
    if [[ -z "$token" ]] && command -v gh > /dev/null 2>&1; then
        token="$(env -u GH_TOKEN -u GITHUB_TOKEN -u GH_ENTERPRISE_TOKEN -u GITHUB_ENTERPRISE_TOKEN \
            GH_DEBUG= DEBUG= gh auth token --hostname "$hostname" 2> /dev/null)" || token=""
    fi
    if [[ -z "$token" || "$token" == *[$'\r\n']* ]]; then
        orcan_die "GitHub authentication unavailable for ${hostname}: set ${token_var} or run gh auth login --hostname ${hostname} on this host"
        return 1
    fi
    export ORCAN_GITHUB_TOKEN="$token"
    githubf="$(orcan_compose_github_file)"
    mkdir -p "$(dirname "$githubf")" || return
    {
        printf '# Generated by orcan up --github; token resolved only at launch.\n'
        printf 'services:\n  orcan:\n    environment:\n'
        printf '      GH_HOST: "%s"\n' "$hostname"
        printf '      GITHUB_TOKEN: ""\n      GITHUB_ENTERPRISE_TOKEN: ""\n'
        if [[ "$token_var" == GH_TOKEN ]]; then
            printf '      GH_ENTERPRISE_TOKEN: ""\n'
        else
            printf '      GH_TOKEN: ""\n'
        fi
        printf '      %s: "${ORCAN_GITHUB_TOKEN:-}"\n' "$token_var"
    } > "$githubf" || return
    if ((traced)); then set -x; fi
}

orcan_compose_network_file() {
    _orcan_compose_file "${ORCAN_COMPOSE_NETWORK:-}" compose-network.generated.yml
}

# Fill nameref array with -f <file> for project mounts (+ optional git overlay).
# Pass with_git=1 as second arg to include compose-git.generated.yml.
orcan_compose_overlay_args() {
    local -n _out="$1"
    local with_git="${2:-0}"
    local projects gitf
    _out=()
    projects="$(orcan_compose_projects_file)"
    _out+=(-f "${projects}")
    if (( with_git )); then
        gitf="$(orcan_compose_git_file)"
        if [[ ! -f "${gitf}" ]]; then
            orcan_die "git overlay missing: ${gitf} (run: orcan up --ssh)"
        fi
        _out+=(-f "${gitf}")
    fi
}

# Write mounts/compose-git.generated.yml for orcan up --ssh.
# Mounts host ~/.ssh (keys/config/known_hosts) and SSH agent when present.
# Does NOT mount ~/.gitconfig (identity comes from GIT_AUTHOR_* via sync).
orcan_write_git_overlay() {
    local gitf ssh_dir sock
    local have_ssh=0 have_agent=0
    gitf="$(orcan_compose_git_file)"
    mkdir -p "$(dirname "${gitf}")"
    ssh_dir="${HOME}/.ssh"
    sock="${SSH_AUTH_SOCK:-}"

    if [[ -d "${ssh_dir}" ]]; then
        have_ssh=1
    fi
    if [[ -n "${sock}" && -S "${sock}" ]]; then
        have_agent=1
    fi
    if (( !have_ssh && !have_agent )); then
        orcan_die "orcan up --ssh needs ${ssh_dir} or a working SSH_AUTH_SOCK"
    fi

    {
        printf '# Generated by orcan up --ssh (do not edit).\n'
        printf 'services:\n'
        printf '  orcan:\n'
        if (( have_agent )); then
            printf '    environment:\n'
            printf '      SSH_AUTH_SOCK: /run/host-ssh-agent.sock\n'
        fi
        printf '    volumes:\n'
        if (( have_ssh )); then
            printf '      - %s:/home/developer/.ssh:ro\n' "${ssh_dir}"
        elif [[ -f "${ssh_dir}/known_hosts" ]]; then
            printf '      - %s:/home/developer/.ssh/known_hosts:ro\n' "${ssh_dir}/known_hosts"
        fi
        if (( have_agent )); then
            printf '      - %s:/run/host-ssh-agent.sock\n' "${sock}"
        fi
    } >"${gitf}"

    printf '%s\n' "${gitf}"
}

# Write mounts/compose-network.generated.yml for orcan up --network <name>.
# Joins an existing (external) Docker network in addition to the default one —
# reachability to sibling containers without mounting the host Docker socket.
orcan_write_network_overlay() {
    local name="$1"
    local netf
    netf="$(orcan_compose_network_file)"
    mkdir -p "$(dirname "${netf}")"

    {
        printf '# Generated by orcan up --network (do not edit).\n'
        printf 'services:\n'
        printf '  orcan:\n'
        printf '    networks:\n'
        printf '      - default\n'
        printf '      - orcan_ext\n'
        printf 'networks:\n'
        printf '  orcan_ext:\n'
        printf '    name: %s\n' "${name}"
        printf '    external: true\n'
    } >"${netf}"

    printf '%s\n' "${netf}"
}

# Default project stays "orcan"; --instance selects its own named project.
orcan_compose_project_args() {
    local -n _out="$1"
    _out=(--project-name "${COMPOSE_PROJECT_NAME:-orcan}")
}

orcan_compose_base() {
    local overlays=() project=()
    orcan_compose_overlay_args overlays 0
    orcan_compose_project_args project
    docker compose \
        "${project[@]}" \
        --env-file "${ORCAN_ENV_FILE}" \
        --project-directory "${ORCAN_ROOT}" \
        -f "${ORCAN_ROOT}/docker-compose.yml" \
        "${overlays[@]}" \
        "$@"
}

orcan_compose_build() {
    local project=()
    orcan_compose_project_args project
    docker compose \
        "${project[@]}" \
        --env-file "${ORCAN_ENV_FILE}" \
        --project-directory "${ORCAN_ROOT}" \
        -f "${ORCAN_ROOT}/docker-compose.yml" \
        "$@"
}

orcan_up_state_file() {
    printf '%s\n' "${ORCAN_RUNTIME_DIR}/up-state.env"
}

# Persist the last `orcan up` overlay combo so down/logs can reuse it.
orcan_write_up_state() {
    local with_docker="${1:-0}"
    local with_git="${2:-0}"
    local with_network="${3:-0}"
    local with_ttyd="${4:-0}"
    local network_name="${5:-}"
    local statef
    statef="$(orcan_up_state_file)"
    mkdir -p "$(dirname "${statef}")"
    {
        printf 'WITH_DOCKER=%s\n' "${with_docker}"
        printf 'WITH_GIT=%s\n' "${with_git}"
        printf 'WITH_NETWORK=%s\n' "${with_network}"
        printf 'WITH_TTYD=%s\n' "${with_ttyd}"
        printf 'NETWORK_NAME=%q\n' "${network_name}"
        printf 'WITH_GITHUB=%s\n' "${6:-0}"
        printf 'GITHUB_HOSTNAME=%q\n' "${7:-}"
        printf 'WITH_GITLAB=%s\n' "${8:-0}"
        printf 'GITLAB_HOSTNAME=%q\n' "${9:-}"
    } >"${statef}"
}

# Last requested `orcan up` flags; unlike up-state.env, `orcan down` keeps it
# so `orcan up --resume` can restore the same stack. Never stores credentials.
orcan_last_up_file() {
    printf '%s\n' "${ORCAN_RUNTIME_DIR}/last-up.env"
}

orcan_write_last_up() {
    local statef
    statef="$(orcan_last_up_file)"
    mkdir -p "$(dirname "${statef}")"
    {
        printf 'WITH_DOCKER=%s\n' "${1:-0}"
        printf 'WITH_GIT=%s\n' "${2:-0}"
        printf 'WITH_NETWORK=%s\n' "${3:-0}"
        printf 'WITH_TTYD=%s\n' "${4:-0}"
        printf 'WITH_TTYD_AUTH=%s\n' "${5:-0}"
        printf 'NETWORK_NAME=%q\n' "${6:-}"
        printf 'WITH_GITHUB=%s\n' "${7:-0}"
        printf 'GITHUB_HOSTNAME=%q\n' "${8:-}"
        printf 'WITH_GITLAB=%s\n' "${9:-0}"
        printf 'GITLAB_HOSTNAME=%q\n' "${10:-}"
    } >"${statef}"
}

orcan_load_up_state() {
    local statef
    statef="$(orcan_up_state_file)"
    [[ -f "${statef}" ]] || return 1
    # shellcheck disable=SC1090
    source "${statef}"
    return 0
}

orcan_clear_up_state() {
    rm -f "$(orcan_up_state_file)"
}

orcan_container_name() {
    printf 'orcan-%s\n' "${ORCAN_INSTANCE:-1}"
}

# Print the running container name or exit with a helpful message.
orcan_require_running_container() {
    orcan_require_docker
    orcan_load_env
    local name
    name="$(orcan_container_name)"
    if ! docker ps -q -f "name=^${name}$" 2>/dev/null | grep -q .; then
        orcan_die "no running container — start with: orcan up   (local: orcan enter; remote browser: orcan up --web-terminal)"
    fi
    printf '%s\n' "${name}"
}

# Compose stack for `orcan up`: optional docker socket, git/SSH, network join, ttyd.
# Usage: orcan_compose_up_run <docker> <git> <network> <ttyd> <github> <gitlab> -- compose args...
orcan_compose_up_run() {
    local with_docker="${1:-0}"
    local with_git="${2:-0}"
    local with_network="${3:-0}"
    local with_ttyd="${4:-0}"
    local with_github="${5:-0}"
    local with_gitlab="${6:-0}"
    shift 6
    local overlays=() project=()
    orcan_compose_overlay_args overlays "${with_git}"
    orcan_compose_project_args project
    local -a cmd=(
        docker compose
        "${project[@]}"
        --env-file "${ORCAN_ENV_FILE}"
        --project-directory "${ORCAN_ROOT}"
        -f "${ORCAN_ROOT}/docker-compose.yml"
        "${overlays[@]}"
    )
    if (( with_ttyd )); then
        cmd+=(-f "${ORCAN_ROOT}/docker-compose.ttyd.yml")
    else
        cmd+=(-f "${ORCAN_ROOT}/docker-compose.keepalive.yml")
    fi
    if (( with_docker )); then
        cmd+=(-f "${ORCAN_ROOT}/docker-compose.docker.yml")
    fi
    if (( with_network )); then
        cmd+=(-f "$(orcan_compose_network_file)")
    fi
    if ((with_github)); then
        cmd+=(-f "$(orcan_compose_github_file)")
    fi
    if ((with_gitlab)); then
        cmd+=(-f "$(orcan_compose_gitlab_file)")
    fi
    "${cmd[@]}" "$@"
}

# Tear down every previously-possible up.sh overlay combo so leftover volume
# mounts from a prior `orcan up` never linger under a mismatched container.
orcan_compose_ttyd_down_all_variants() {
    local git_variants=(0) network_variants=(0)
    [[ -f "$(orcan_compose_git_file)" ]] && git_variants+=(1)
    [[ -f "$(orcan_compose_network_file)" ]] && network_variants+=(1)
    local d g n t
    for t in 0 1; do
        for d in 0 1; do
            for g in "${git_variants[@]}"; do
                for n in "${network_variants[@]}"; do
                    orcan_compose_up_run "${d}" "${g}" "${n}" "${t}" 0 0 down --remove-orphans > /dev/null 2>&1 || true
                done
            done
        done
    done
    orcan_clear_up_state
}

orcan_require_generated() {
    ORCAN_HOME="${ORCAN_HOME}" ORCAN_ROOT="${ORCAN_ROOT}" \
        "${ORCAN_SCRIPTS}/require-generated.sh"
}
