#!/usr/bin/env bash
# Docker Compose wrappers — files from ORCAN_ROOT, env/overlays from ORCAN_HOME.
# shellcheck shell=bash

orcan_compose_projects_file() {
    local from_env
    from_env="${ORCAN_COMPOSE_PROJECTS:-}"
    if [[ -n "${from_env}" ]]; then
        printf '%s\n' "${from_env}"
    else
        printf '%s\n' "${ORCAN_RUNTIME_DIR}/compose-projects.generated.yml"
    fi
}

orcan_compose_git_file() {
    local from_env
    from_env="${ORCAN_COMPOSE_GIT:-}"
    if [[ -n "${from_env}" ]]; then
        printf '%s\n' "${from_env}"
    else
        printf '%s\n' "${ORCAN_RUNTIME_DIR}/compose-git.generated.yml"
    fi
}

# Fill nameref array with -f <file> for project mounts (+ optional git overlay).
# Pass with_git=1 as second arg to include compose-git.generated.yml.
orcan_compose_overlay_args() {
    local -n _out="$1"
    local with_git="${2:-0}"
    local projects gitf
    _out=()
    projects="$(orcan_compose_projects_file)"
    _out+=(-f "${projects}")
    if (( with_git )); then
        gitf="$(orcan_compose_git_file)"
        if [[ ! -f "${gitf}" ]]; then
            orcan_die "git overlay missing: ${gitf} (run: orcan up --with-git)"
        fi
        _out+=(-f "${gitf}")
    fi
}

# Write .orcan/compose-git.generated.yml for orcan up --with-git.
# Mounts host ~/.ssh (keys/config/known_hosts) and SSH agent when present.
# Does NOT mount ~/.gitconfig (identity comes from GIT_AUTHOR_* via sync).
orcan_write_git_overlay() {
    local gitf ssh_dir sock
    local have_ssh=0 have_agent=0
    gitf="$(orcan_compose_git_file)"
    mkdir -p "$(dirname "${gitf}")"
    ssh_dir="${HOME}/.ssh"
    sock="${SSH_AUTH_SOCK:-}"

    if [[ -d "${ssh_dir}" ]]; then
        have_ssh=1
    fi
    if [[ -n "${sock}" && -S "${sock}" ]]; then
        have_agent=1
    fi
    if (( !have_ssh && !have_agent )); then
        orcan_die "orcan up --with-git needs ${ssh_dir} or a working SSH_AUTH_SOCK"
    fi

    {
        printf '# Generated by orcan up --with-git (do not edit).\n'
        printf 'services:\n'
        printf '  orcan:\n'
        if (( have_agent )); then
            printf '    environment:\n'
            printf '      SSH_AUTH_SOCK: /run/host-ssh-agent.sock\n'
        fi
        printf '    volumes:\n'
        if (( have_ssh )); then
            printf '      - %s:/home/developer/.ssh:ro\n' "${ssh_dir}"
        elif [[ -f "${ssh_dir}/known_hosts" ]]; then
            printf '      - %s:/home/developer/.ssh/known_hosts:ro\n' "${ssh_dir}/known_hosts"
        fi
        if (( have_agent )); then
            printf '      - %s:/run/host-ssh-agent.sock\n' "${sock}"
        fi
    } >"${gitf}"

    printf '%s\n' "${gitf}"
}

# Always use Compose project "orcan" (container: orcan-1 via docker-compose.yml).
orcan_compose_project_args() {
    local -n _out="$1"
    _out=(--project-name "${COMPOSE_PROJECT_NAME:-orcan}")
}

orcan_compose_base() {
    local overlays=() project=()
    orcan_compose_overlay_args overlays 0
    orcan_compose_project_args project
    docker compose \
        "${project[@]}" \
        --env-file "${ORCAN_ENV_FILE}" \
        --project-directory "${ORCAN_ROOT}" \
        -f "${ORCAN_ROOT}/docker-compose.yml" \
        "${overlays[@]}" \
        "$@"
}

orcan_compose_build() {
    local project=()
    orcan_compose_project_args project
    docker compose \
        "${project[@]}" \
        --env-file "${ORCAN_ENV_FILE}" \
        --project-directory "${ORCAN_ROOT}" \
        -f "${ORCAN_ROOT}/docker-compose.yml" \
        "$@"
}

# Terminal compose: optional docker socket + optional git/SSH mounts.
# Usage: orcan_compose_ttyd_run <with_docker 0|1> <with_git 0|1> -- compose args...
orcan_compose_ttyd_run() {
    local with_docker="${1:-0}"
    local with_git="${2:-0}"
    shift 2
    local overlays=() project=()
    orcan_compose_overlay_args overlays "${with_git}"
    orcan_compose_project_args project
    local -a cmd=(
        docker compose
        "${project[@]}"
        --env-file "${ORCAN_ENV_FILE}"
        --project-directory "${ORCAN_ROOT}"
        -f "${ORCAN_ROOT}/docker-compose.yml"
        "${overlays[@]}"
        -f "${ORCAN_ROOT}/docker-compose.ttyd.yml"
    )
    if (( with_docker )); then
        cmd+=(-f "${ORCAN_ROOT}/docker-compose.docker.yml")
    fi
    "${cmd[@]}" "$@"
}

orcan_compose_ttyd() {
    orcan_compose_ttyd_run 0 0 "$@"
}

orcan_compose_ttyd_docker() {
    orcan_compose_ttyd_run 1 0 "$@"
}

orcan_require_generated() {
    ORCAN_HOME="${ORCAN_HOME}" ORCAN_ROOT="${ORCAN_ROOT}" \
        "${ORCAN_SCRIPTS}/require-generated.sh"
}
